Verify existence of stripped dlls

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -32,7 +32,14 @@ jobs:
         sparse-checkout: |
           Versions/${{ steps.read-json.outputs.game_version }}
         sparse-checkout-cone-mode: false
-     
+        
+    - name: Verify that stripped dlls actually exist
+      run: |
+        if [ -z "$(ls -A Stripped/Versions/${{ steps.read-json.outputs.game_version }})" ]; then
+          echo "Error: Stripped dependencies folder is empty!"
+          exit 1
+        fi
+        
     - name: Move stripped dlls to refs
       run: mv Stripped/Versions/${{ steps.read-json.outputs.game_version }} Refs
     
